[project]
name = "ha-virtual-devices"
version = "0.1.0"
description = "Virtual composite devices for Home Assistant"
readme = "README.md"
requires-python = ">=3.14.2"
license = "MIT"
authors = [{ name = "Sebastian Bolek" }]
dependencies = []

[dependency-groups]
dev = [
    "mypy==2.3.1",
    "pytest-homeassistant-custom-component==0.13.357",
    "ruff==0.16.5",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
addopts = ["--strict-config", "--strict-markers"]
asyncio_mode = "auto"
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
required-version = ">=0.16.5"
src = ["custom_components", "tests"]
target-version = "py314"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
ignore = ["D203", "D213"]
select = [
    "ASYNC",
    "B",
    "D",
    "E",
    "F",
    "G",
    "I",
    "LOG",
    "PIE",
    "PT",
    "PYI",
    "RUF",
    "SIM",
    "T10",
    "TC",
    "UP",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D", "S101"]

[tool.mypy]
python_version = "3.14"
explicit_package_bases = true
show_error_codes = true
strict = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
