"""Constants for the Virtual Devices integration."""

from typing import Final

DOMAIN: Final = "virtual_devices"

CONF_DEVICE_ID: Final = "device_id"
CONF_CONFIG_VERSION: Final = "config_version"
CONF_CONTROL_MODE: Final = "control_mode"
CONF_STEP_SOURCE: Final = "step_source"
CONF_OPEN_SOURCE: Final = "open_source"
CONF_CLOSE_SOURCE: Final = "close_source"
CONF_STOP_SOURCE: Final = "stop_source"
CONF_OPEN_LIMIT: Final = "open_limit"
CONF_CLOSED_LIMIT: Final = "closed_limit"
CONF_OPEN_LIMIT_ACTIVE_STATE: Final = "open_limit_active_state"
CONF_CLOSED_LIMIT_ACTIVE_STATE: Final = "closed_limit_active_state"
CONF_OPEN_LIMIT_DEBOUNCE_MS: Final = "open_limit_debounce_ms"
CONF_CLOSED_LIMIT_DEBOUNCE_MS: Final = "closed_limit_debounce_ms"
CONF_OBSTACLE_SOURCE: Final = "obstacle_source"
CONF_OPENING_TIME_MS: Final = "opening_time_ms"
CONF_CLOSING_TIME_MS: Final = "closing_time_ms"
CONF_OPENING_MARGIN_MS: Final = "opening_margin_ms"
CONF_CLOSING_MARGIN_MS: Final = "closing_margin_ms"
CONF_PULSE_DURATION_MS: Final = "pulse_duration_ms"
CONF_HOLD_DURATION_MS: Final = "hold_duration_ms"
CONF_MINIMUM_COMMAND_INTERVAL_MS: Final = "minimum_command_interval_ms"
CONF_DIRECTION_CHANGE_DELAY_MS: Final = "direction_change_delay_ms"
CONF_PULSE_INTERVAL_MS: Final = "pulse_interval_ms"
CONF_PULSE_COUNT: Final = "pulse_count"
CONF_STOP_STRATEGY: Final = "stop_strategy"
CONF_DIRECTION_CHANGE_STRATEGY: Final = "direction_change_strategy"
CONF_REPEATED_OPEN_POLICY: Final = "repeated_open_policy"
CONF_REPEATED_CLOSE_POLICY: Final = "repeated_close_policy"
